[tasks.test]
run = "cargo test -- --test-threads 1 --nocapture"

[tasks.cap]
run = "cargo test"

[tasks.trace]
env.RUST_BACKTRACE = 1
run = "cargo test"

[tasks.build]
raw_args = true
run = "cargo build"

[tasks.crun]
raw_args = true
alias = "r"
run = "cargo run"

[tasks.clean]
run = "cargo clean"

[tasks.upgrade]
run = "cargo upgrade -i"

[tasks.clippy]
run = "bacon clippy"

[tasks.psql]
run = "PGPASSWORD=test psql 'postgres://unexist@localhost/foo?sslmode=disable'"
